### ISSUE TITLE
mDNS timeout.

### ISSUE THREAD

**Issue by siamkater** [horihiro/esp8266-google-home-notifier#13] opened 2019-01-10 16:50 UTC
Hello,
i own 5 google home speaker and all up and running but
It does not matter what google home name I enter, I only get this error
 
connecting to Wi-Fi.
connected.
IP address: *92.*68.*88.*84
connecting to Google Home...
mDNS timeout.

can you help me ?

**Comment by horihiro** [comment] 2019-01-11 00:48
could you please let me know whether this issue is reproduced if only one google home is turned on?

and which do you use, esp8266 or esp32?

**Comment by siamkater** [comment] 2019-01-11 11:10
shame on me displayname is case sensitive after i changed this it works.
 BUT the next problem i have is the speaker plays the signal tone but the text is missing this happens all 2-3 times. in the log i get no error.

connecting to Google Home...
found Google Home
192.168.188.54
:
8009
)
Done.

and i dont know if this feature talk to a group should work
if yes then i have the following problem
one speaker plays the notificatinon sound and sometimes a other speaker plays the text 

connecting to Google Home...
found Google Home
192.168.188.61
:
42524
)
Done.

i use the esp8266

**Comment by horihiro** [comment] 2019-01-11 13:54
sorry , I'm not sure that this library can make multiple google homes speak because i have only one google home.

do your google homes share same display name?

**Comment by siamkater** [comment] 2019-01-11 14:01
no they don't share the same display name 
in the google home app you can add the speaker to a group with a new display name for the group

**Comment by horihiro** [comment] 2019-01-12 02:30
I'm not sure that speaker **group** is related to this issue.

If you know, could you please let me know the reproducing steps of this issue when there is one Google Home,?

**Comment by horihiro** [comment] 2019-02-11 09:27
I close this issue once.
Please open again when repro steps is discovered.

**Closed as completed by horihiro** 2019-02-11 09:27 UTC
